version: '3.3'

services:
   db:
     container_name: mysql
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: <db_root_password>
       MYSQL_DATABASE: <db_name>
       MYSQL_USER: <db_user_name>
       MYSQL_PASSWORD: <db_user_password>

   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "<IP>:8080:80"
       - "<IP>:8000:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
        - wordpress_data:/var/www/html
volumes:
    db_data: {}
    wordpress_data: {}
